"""
JSON file validation utilities.

Provides reusable functions for validating JSON files generated by the
legacy and modern code. Automatically detects and reports invalid,
corrupted, or empty JSON files.
"""

import json
from pathlib import Path
from typing import Dict, Optional, Tuple, List, Any


class JsonValidationError(Exception):
    """Exception raised when JSON validation fails."""
    pass


class JsonValidator:
    """Validator for JSON files generated by legacy and modern code."""
    
    @staticmethod
    def validate_file(json_file: Path) -> Tuple[bool, Optional[str]]:
        """
        Validate a JSON file.
        
        Args:
            json_file: Path to JSON file to validate
            
        Returns:
            Tuple of (is_valid, error_message)
            - is_valid: True if file is valid, False otherwise
            - error_message: None if valid, error description if invalid
        """
        if not json_file.exists():
            return False, "File does not exist"
        
        # Check file size
        try:
            file_size = json_file.stat().st_size
            if file_size == 0:
                return False, "File is empty"
        except OSError as e:
            return False, f"Cannot read file: {str(e)}"
        
        # Try to parse JSON
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            return False, f"Invalid JSON syntax: {str(e)}"
        except Exception as e:
            return False, f"Error reading file: {str(e)}"
        
        # Validate structure
        return JsonValidator.validate_data(data)
    
    @staticmethod
    def validate_data(data: Any) -> Tuple[bool, Optional[str]]:
        """
        Validate JSON data structure.
        
        Args:
            data: Parsed JSON data (dict, list, etc.)
            
        Returns:
            Tuple of (is_valid, error_message)
        """
        # Check if it's a valid JSON object
        if not isinstance(data, dict):
            return False, "JSON is not an object (expected dict)"
        
        # Check for required fields
        if "pdb_name" not in data:
            return False, "Missing required field: 'pdb_name'"
        
        if "calculations" not in data:
            return False, "Missing required field: 'calculations'"
        
        # Check if calculations is an array
        if not isinstance(data["calculations"], list):
            return False, "Field 'calculations' is not an array"
        
        # Check if calculations array is empty
        if len(data["calculations"]) == 0:
            return False, "Field 'calculations' array is empty"
        
        # Check if at least one calculation has meaningful data
        has_data = JsonValidator._has_meaningful_data(data["calculations"])
        
        if not has_data:
            return False, "No meaningful data in calculations array"
        
        return True, None
    
    @staticmethod
    def _has_meaningful_data(calculations: List[Dict[str, Any]]) -> bool:
        """
        Check if calculations array contains meaningful data.
        
        Args:
            calculations: List of calculation records
            
        Returns:
            True if at least one calculation has meaningful data
        """
        for calc in calculations:
            if not isinstance(calc, dict):
                continue
            
            calc_type = calc.get("type")
            if not calc_type:
                continue
            
            # Check based on calculation type
            if calc_type == "pdb_atoms":
                # Must have atoms array with at least one atom
                atoms = calc.get("atoms", [])
                if isinstance(atoms, list) and len(atoms) > 0:
                    return True
            
            elif calc_type in ["base_frame_calc", "frame_calc", "ls_fitting"]:
                # Must have residue_idx or other identifying fields
                if "residue_idx" in calc:
                    return True
                # Or check for rotation_matrix/translation
                if "rotation_matrix" in calc or "translation" in calc:
                    return True
            
            elif calc_type == "base_pair":
                # Must have base indices
                if "base_i" in calc and "base_j" in calc:
                    return True
            
            elif calc_type == "bpstep_params":
                # Must have parameter values
                if any(key in calc for key in ["Shift", "Slide", "Rise", "Tilt", "Roll", "Twist"]):
                    return True
            
            elif calc_type == "helical_params":
                # Must have helical parameter values
                if any(key in calc for key in ["Xp", "Yp", "Zp", "XpH", "YpH", "ZpH"]):
                    return True
            
            elif calc_type in ["removed_atom", "removed_atoms_summary"]:
                # These are metadata, count as meaningful
                return True
            
            else:
                # For other types, check if calc has any keys beyond "type"
                other_keys = [k for k in calc.keys() if k != "type"]
                if len(other_keys) > 0:
                    return True
        
        return False
    
    @staticmethod
    def remove_invalid_file(json_file: Path, reason: Optional[str] = None) -> bool:
        """
        Remove an invalid JSON file.
        
        Args:
            json_file: Path to JSON file to remove
            reason: Optional reason for removal (for logging)
            
        Returns:
            True if file was removed, False if removal failed
        """
        try:
            if json_file.exists():
                json_file.unlink()
                return True
        except Exception as e:
            # Don't raise - just return False
            return False
        return False
    
    @staticmethod
    def validate_and_clean(json_file: Path, remove_invalid: bool = True) -> Tuple[bool, Optional[str], bool]:
        """
        Validate a JSON file and optionally remove if invalid.
        
        Args:
            json_file: Path to JSON file to validate
            remove_invalid: If True, remove file if invalid
            
        Returns:
            Tuple of (is_valid, error_message, was_removed)
            - is_valid: True if file is valid
            - error_message: None if valid, error description if invalid
            - was_removed: True if file was removed, False otherwise
        """
        is_valid, error_msg = JsonValidator.validate_file(json_file)
        
        if not is_valid and remove_invalid:
            was_removed = JsonValidator.remove_invalid_file(json_file, error_msg)
            return False, error_msg, was_removed
        
        return is_valid, error_msg, False
    
    @staticmethod
    def get_validation_summary(json_file: Path) -> Dict[str, Any]:
        """
        Get detailed validation summary for a JSON file.
        
        Args:
            json_file: Path to JSON file
            
        Returns:
            Dictionary with validation details
        """
        summary = {
            'file': str(json_file),
            'exists': json_file.exists(),
            'is_valid': False,
            'error': None,
            'file_size': 0,
            'has_pdb_name': False,
            'calculations_count': 0,
            'calculation_types': [],
            'has_meaningful_data': False,
        }
        
        if not json_file.exists():
            summary['error'] = "File does not exist"
            return summary
        
        try:
            summary['file_size'] = json_file.stat().st_size
        except OSError:
            summary['error'] = "Cannot read file"
            return summary
        
        if summary['file_size'] == 0:
            summary['error'] = "File is empty"
            return summary
        
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            summary['error'] = f"Invalid JSON: {str(e)}"
            return summary
        except Exception as e:
            summary['error'] = f"Error reading file: {str(e)}"
            return summary
        
        # Validate structure
        is_valid, error_msg = JsonValidator.validate_data(data)
        summary['is_valid'] = is_valid
        summary['error'] = error_msg
        
        if is_valid:
            summary['has_pdb_name'] = 'pdb_name' in data
            summary['calculations_count'] = len(data.get('calculations', []))
            summary['calculation_types'] = [
                calc.get('type') for calc in data.get('calculations', [])
                if isinstance(calc, dict) and 'type' in calc
            ]
            summary['has_meaningful_data'] = JsonValidator._has_meaningful_data(
                data.get('calculations', [])
            )
        
        return summary

