/**
 * @file parameters_generated.hpp
 * @brief Auto-generated compile-time constants from parameters.json
 *
 * Generated: 2025-12-18T15:38:49.557068
 * Source: resources/config/parameters.json
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit parameters.json and rebuild (CMake runs generate_parameters.py automatically)
 */

#pragma once

namespace x3dna {
namespace config {
namespace params {

// Numeric tolerances
constexpr double XEPS = 1e-10;
constexpr double XEPS_LS = 1e-07;
constexpr double EPSILON_VECTOR = 1e-09;
constexpr double EMPTY_CRITERION = 1e-10;
constexpr double PROTOCOL_TOLERANCE = 1e-06;

// Numeric limits
constexpr double XBIG = 1e18;
constexpr double SMALL_NUMBER = 1e-10;
constexpr double MAX_VALID_SCORE = 1e17;

// Numeric constants
constexpr double PI = 3.141592653589793;

// Geometry
constexpr double COVALENT_BOND_MAX = 2.0;
constexpr double SAME_ATOM_THRESHOLD = 0.1;

// Quality score
constexpr double D_V_WEIGHT = 2.0;
constexpr double PLANE_ANGLE_DIVISOR = 20.0;
constexpr double WC_QUALITY_BONUS = 2.0;
constexpr double WC_PAIR_BONUS = -2.0;
constexpr double GOOD_HBOND_ADJUSTMENT = -3.0;
constexpr int MIN_GOOD_HBONDS_FOR_BONUS = 2;
constexpr double GOOD_HBOND_MIN_DIST = 2.5;
constexpr double GOOD_HBOND_MAX_DIST = 3.5;

// Pair classification
constexpr double WC_SHEAR_MAX = 1.8;
constexpr double WOBBLE_SHEAR_MIN = 1.8;
constexpr double WOBBLE_SHEAR_MAX = 2.8;
constexpr double STRETCH_THRESHOLD = 2.0;
constexpr double OPENING_THRESHOLD = 60.0;

// Hydrogen bond conflict
constexpr int HB_CONFLICT_MARKER = 9;
constexpr int HB_LINKAGE_CONFLICT = 18;

// Validation thresholds
constexpr double MIN_DORG = 0.0;
constexpr double MAX_DORG = 15.0;
constexpr double MIN_DV = 0.0;
constexpr double MAX_DV = 2.5;
constexpr double MIN_DNN = 4.5;
constexpr double MAX_DNN = 1e18;
constexpr double MIN_PLANE_ANGLE = 0.0;
constexpr double MAX_PLANE_ANGLE = 65.0;
constexpr double OVERLAP_THRESHOLD = 0.01;

// Hydrogen bond
constexpr double HB_LOWER = 1.8;
constexpr double HB_DIST1 = 4.0;
constexpr double HB_DIST2 = 0.0;
constexpr const char* HB_ATOMS = ".O.N";
constexpr double HB_GOOD_MIN = 2.5;
constexpr double HB_GOOD_MAX = 3.5;
constexpr double HB_FILTER_MAX = 3.6;
constexpr double HB_NONSTANDARD_MIN = 2.6;
constexpr double HB_NONSTANDARD_MAX = 3.2;
constexpr double HB_DEFAULT_DIST2 = 4.5;
constexpr int MIN_BASE_HB = 1;

// Nucleotide identification
constexpr double NT_RMSD_CUTOFF = 0.2618;
constexpr double DNN_FALLBACK = 1e10;
constexpr double BOND_DISTANCE = 2.0;
constexpr double MIN_ATOM_DISTANCE = 0.1;

// Helix organization
constexpr double HELIX_BREAK = 7.8;
constexpr double END_STACK_XANG = 125.0;
constexpr double STD_CURVED = 0.6;

// Water
constexpr double WATER_DIST = 3.2;
constexpr double WATER_DLOW = 0.0;
constexpr const char* WATER_ATOMS = ".O.N";

// Miscellaneous
constexpr const char* ALT_LIST = "A1";
constexpr double O3P_DIST = 4.5;
constexpr double GAMUT = 500000000.0;

} // namespace params
} // namespace config
} // namespace x3dna
