#!/usr/bin/env python3
"""Create a plan for comparing parameters between legacy and modern for matching pairs."""

import sys
from pathlib import Path

def main():
    project_root = Path(__file__).parent.parent
    
    print("="*80)
    print("PARAMETER COMPARISON PLAN")
    print("="*80)
    print()
    print("Goal: Verify that for matching base pairs, all calculated parameters")
    print("      (step and helical) match between legacy and modern code.")
    print()
    print("="*80)
    print("APPROACH")
    print("="*80)
    print()
    print("1. IDENTIFY PERFECT MATCHES")
    print("   - Use large_sweep_analysis.py to find PDBs where pairs match exactly")
    print("   - Filter for cases with meaningful number of pairs (>5)")
    print("   - Examples: 6V9Q (7 pairs), 7EH2 (24 pairs), 1A34 (9 pairs)")
    print()
    print("2. EXTRACT LEGACY PARAMETERS")
    print("   - Run legacy analyze on .inp files")
    print("   - Parse bp_step.par and bp_helical.par files")
    print("   - Extract all 6 step parameters and 6 helical parameters per step")
    print()
    print("3. EXTRACT MODERN PARAMETERS")
    print("   - Run modern analyze_app on .inp files")
    print("   - Parse stdout output (or JSON if available)")
    print("   - Extract all 6 step parameters and 6 helical parameters per step")
    print()
    print("4. COMPARE PARAMETERS")
    print("   - For each step, compare all 12 parameters (6 step + 6 helical)")
    print("   - Use tolerance: 0.01 for numerical comparison")
    print("   - Report any differences above tolerance")
    print()
    print("5. VALIDATE")
    print("   - Check that parameter counts match")
    print("   - Verify no zero/NaN values (except where expected)")
    print("   - Confirm parameter order matches legacy")
    print()
    print("="*80)
    print("PARAMETERS TO COMPARE")
    print("="*80)
    print()
    print("Step Parameters (per base pair step):")
    print("  1. Shift  (Å)")
    print("  2. Slide  (Å)")
    print("  3. Rise   (Å)")
    print("  4. Tilt   (degrees)")
    print("  5. Roll   (degrees)")
    print("  6. Twist  (degrees)")
    print()
    print("Helical Parameters (per base pair step):")
    print("  1. X-disp        (Å)")
    print("  2. Y-disp        (Å)")
    print("  3. h-Rise        (Å)")
    print("  4. Inclination   (degrees)")
    print("  5. Tip           (degrees)")
    print("  6. h-Twist       (degrees)")
    print()
    print("="*80)
    print("CHALLENGES")
    print("="*80)
    print()
    print("1. Legacy .par file format")
    print("   - Need to parse bp_step.par and bp_helical.par correctly")
    print("   - Format may vary for different structure types")
    print()
    print("2. Step numbering")
    print("   - Legacy may use 1-based indexing")
    print("   - Modern uses 0-based internally but 1-based in output")
    print("   - Need to align step numbers correctly")
    print()
    print("3. Output format differences")
    print("   - Legacy writes to .par files")
    print("   - Modern writes to stdout (or could write to files)")
    print("   - Need consistent parsing")
    print()
    print("="*80)
    print("IMPLEMENTATION STEPS")
    print("="*80)
    print()
    print("Step 1: Create legacy parameter extractor")
    print("  - Script to parse bp_step.par and bp_helical.par")
    print("  - Handle different format variations")
    print()
    print("Step 2: Enhance modern parameter extractor")
    print("  - Already have extract_modern_parameters()")
    print("  - May need to handle JSON output option")
    print()
    print("Step 3: Create comparison function")
    print("  - Compare step-by-step with tolerance")
    print("  - Report differences clearly")
    print()
    print("Step 4: Test on perfect matches")
    print("  - Run on 6V9Q, 7EH2, 1A34")
    print("  - Verify all parameters match")
    print()
    print("Step 5: Expand to all perfect matches")
    print("  - From large sweep, identify all perfect matches")
    print("  - Run comparison on all")
    print("  - Generate report")
    print()
    print("="*80)
    print("SUCCESS CRITERIA")
    print("="*80)
    print()
    print("✅ For all perfect matches:")
    print("   - All step parameters match (tolerance: 0.01)")
    print("   - All helical parameters match (tolerance: 0.01)")
    print("   - Parameter counts match")
    print("   - No missing or invalid values")
    print()

if __name__ == "__main__":
    main()

